spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kevinlee12138/config-repo.git
          username: kevin12138az@163.com
          password: 3721.lei
          basedir: D:\workspace\idea\springcloud\cloud-muliti\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


debug: true
server:
  port: 8083
